// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorGoldenZebra.Models;

public partial class Order
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public DateTime DateCreate { get; set; }

    public int PlaceId { get; set; }

    public string UserId { get; set; }

    public string Comment { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Place Place { get; set; }

    public virtual AspNetUser User { get; set; }
}