// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorGoldenZebra.Models;

public partial class Place
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string House { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}