// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BlazorGoldenZebra.Utills;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Reflection.Emit;

namespace BlazorGoldenZebra.Models;

public partial class GoldenZebraSecurityContext : DbContext
{
    public GoldenZebraSecurityContext(DbContextOptions<GoldenZebraSecurityContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<MetalType> MetalTypes { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Place> Places { get; set; }

    public virtual DbSet<ProductType> ProductTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        Console.WriteLine($"{DateTime.Now} OnModelCreating Start");

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            if (ConfigSettings.UsePostgres)
            {
                entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique();
            }
            else
            {
                entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");
            }
                

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");
            if (ConfigSettings.UsePostgres)
            {
                entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique();
            }
            else
            {
                entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");
            }


                entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<MetalType>(entity =>
        {
            entity.Property(e => e.DefaultFiness).HasDefaultValue(999);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(256);

            entity.HasData(
                    new MetalType() { Id = 1, Name = "Золото", DefaultFiness = 585 },
                    new MetalType() { Id = 2, Name = "Серебро", DefaultFiness = 925 },
                    new MetalType() { Id = 3, Name = "Платина", DefaultFiness = 950 },
                    new MetalType() { Id = 4, Name = "Палладий", DefaultFiness = 999 }
                );
        });

        Console.WriteLine($"{DateTime.Now} OnModelCreating Middle");

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.ToTable("Movie");

            entity.Property(e => e.Genre).IsRequired();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Title).IsRequired();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            if (ConfigSettings.UsePostgres)
            {
                entity.Property(e => e.Date).HasColumnType("timestamp");
                entity.Property(e => e.DateCreate).HasColumnType("timestamp");
            }
            else
            {
                entity.Property(e => e.Date).HasColumnType("datetime");
                entity.Property(e => e.DateCreate).HasColumnType("datetime");
            }

            entity.Property(e => e.UserId).HasMaxLength(450);

            entity.Property(e => e.Comment).HasColumnType("text");

            entity.HasOne(d => d.Place).WithMany(p => p.Orders)
                .HasForeignKey(d => d.PlaceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Places");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Orders_AspNetUsers");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.Property(e => e.WeightClean).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.WeightDirty).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Cost).HasColumnType("decimal(18, 2)");

            //entity.HasOne(d => d.MetalTypeNavigation).WithMany(p => p.OrderItems)
            //    .HasForeignKey(d => d.MetalType)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK_OrderItems_MetalTypes");

            //entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
            //    .HasForeignKey(d => d.OrderId)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK_OrderItems_Orders");

            //entity.HasOne(d => d.ProductTypeNavigation).WithMany(p => p.OrderItems)
            //    .HasForeignKey(d => d.ProductType)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK_OrderItems_ProductTypes");
        });

        modelBuilder.Entity<Place>(entity =>
        {
            entity.Property(e => e.City).HasMaxLength(256);
            entity.Property(e => e.House).HasMaxLength(32);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Street).HasMaxLength(256);
        });

        modelBuilder.Entity<ProductType>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(512);
            entity.HasData(
                    new ProductType() { Id = 1, Name = "Лом"},
                    new ProductType() { Id = 2, Name = "Изделие" }
                );
        });

        OnModelCreatingPartial(modelBuilder);

        Console.WriteLine($"{DateTime.Now} OnModelCreating End");
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}