// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorGoldenZebra.Models;

public partial class OrderItem
{
    public int Id { get; set; }

    public int MetalType { get; set; }

    public int ProductType { get; set; }

    public int OrderId { get; set; }

    public decimal WeightDirty { get; set; }

    public decimal? WeightClean { get; set; }

    public int Fineness { get; set; }

    public decimal Cost { get; set; }
}